name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace placeholders in env.js
        run: |
          sed -i "s/YOUR_GOOGLE_MAPS_API_KEY/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" env.js
          sed -i "s/YOUR_AUTH0_DOMAIN/${{ secrets.AUTH0_DOMAIN }}/g" env.js
          sed -i "s/YOUR_AUTH0_CLIENT_ID/${{ secrets.AUTH0_CLIENT_ID }}/g" env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./