name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate env.js
        run: |
          echo "window.__ENV = { \
            GOOGLE_MAPS_API_KEY: '${{ secrets.GOOGLE_MAPS_API_KEY }}', \
            AUTH0_DOMAIN: '${{ secrets.AUTH0_DOMAIN }}', \
            AUTH0_CLIENT_ID: '${{ secrets.AUTH0_CLIENT_ID }}' \
          };" > env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES }}
          publish_dir: ./